import { Cliente } from "./cliente";
//import { ReporteTecnico } from "./reportetecnico";
export class EquipoCliente {
  idEquipo!: number;
  codigoequipo!: string;
  codigoequipocliente!: string;
  nombre!: string;
  nombrecliente!:string;
  categoria_equipo!: string;
  marca!: string;
  modelo!:string;
  numero_serie!:string;
  capacidad!:string;
  capacidad_maxima!: string;
  capacidad_minima!: string;
  resolucion!: string;
  divisiones!: string;
  observaciones!: string;
 // imagen_equipo!: File;
  unidad_medida!: string;
  instrumento!: string;
  mide!: string;
  lista_precio!: string;
  cmc_equipo!: string;
  fabricante_receptor!: string;
  modelo_receptor!: string;
  serie_receptor!: string;
  id_interno_receptor!: string;
  fabricante_sensor!: string;
  modelo_sensor!: string;
  id_interno_sensor!: string;
  serie_sensor!: string;
  fabricante_indicador!: string;
  modelo_indicador!: string;
  serie_indicador!: string;
  id_interno_indicador!: string;
  createAt!: Date;
  activo!: boolean;
  cliente!: Cliente;
}
