import { Cliente } from "./cliente";
import { EquipoCliente } from "./equipocliente";

export class OrdenTrabajo {
  idOT!: number;
  no_ordent!: string;
  no_solicitud!: string;
  no_ordencompra!: string;
  no_cotizacion!: string;
  fecha_entrega_certificado!: Date;
  no_certificado!: string;
  no_reporte_tecnico!: string;
  metrologo_responsable!: string;
  fecha_calibracion!: Date;
  prox_calibracion!: boolean;
  nombre_equipo!:string;
  nombre_cliente!: string;
  direccion_cliente!: string;
  usuario_final!: string;
  lugar_calibracion!: string;
  contacto_cliente!: string;
  telefono_contacto!: string;
  cargo!: string;
  correo!: string;
  contacto_cargo!: string;
  descripcion_recep!: string;
  fabricante_ind!: string;
  modelo_ind!: string;
  serie_ind!: string;
  clase_ind!: string;
  alcance!: string;
  fabricande_rec!: string;
  modelo_rec!: string;
  serie_rec!: string;
  resolucion!: string;
  fabricante_sen!: string;
  modelo_sen!: string;
  serie_sen!: string;
  observaciones!: string;
  rechazotecno!: boolean;
  motivo!: string;
  nombre_entrega!: string;
  cedula!: string;
  fecha_entrega!: Date;
  metrologo_entrega!: string;
  recibe_ibc!: string;
  entrego_con_ibc!: boolean;
  observaciones_entrega!: string;
  fecha_entrega_ibc!: Date;
  es_fecha_entrga!: boolean;
  persona_entrega_ibc!: string;
  recibe_certificado!: string;
  recibe_cedula!: string;
  activo!: boolean;
  cliente!: Cliente;
  equipo!: EquipoCliente;
}
