import { Cliente } from "./cliente";
import { EquipoCliente } from "./equipocliente";

export class ReporteTecnico {
  idreptec!: number;
  nombrecliente!:string;
  nombreequipo!:string;
  no_reporte_tecnico!: string;
  no_cotizacion!: string;
  tecnico!: string;
  horaentrada!: Date;
  horasalida!: Date;
  horaviajes!: string;
  fechareporte!: Date;
  contacto!: string;
  direccion!: string;
  marca!: string;
  modelo!: string;
  no_serie!: string;
  ubicacion_equipo!: string;
  idinterno!: string;
  capacidad!: string;
  resolucion!: string;
  calibracion!: boolean;
  instalacion!: boolean;
  verificacion!: boolean;
  entregaequipo!: boolean;
  gestionmetrologica!: boolean;
  retiroequipo!: boolean;
  inspeccion!: boolean;
  otros!: boolean;
  observaciones!: string;
  desnivel!: boolean;
  vibraciones!: boolean;
  averias!: boolean;
  erroresindicador!: boolean;
  soporteinadecuadas!: boolean;
  faltacomponente!: boolean;
  suceidad!: boolean;
  corrienteaire!: boolean;
  insectos!: boolean;
  golpe!: boolean;
  fuentexternacalor!: boolean;
  configuracion!: boolean;
  observaciones2!: string;
  nivelacion!: boolean;
  limpieza!: boolean;
  ajusteslinealidad!: boolean;
  configuracion1!: boolean;
  ajusteexcentricidad!: boolean;
  reemplazo!: boolean;
  observaciones3!: string;
  completo!: boolean;
  incompleto!: boolean;
  observaciones4!: string;
  nota!: string;
  recibidopor!: string;
  fecha!: Date;
  activo!: boolean;
  descripcion_1!: string;
  descripcion_2!: string;
  descripcion_3!: string;
  descripcion_4!: string;
  rutaImagen1!: string;
  rutaImagen2!: string;
  rutaImagen3!: string;
  rutaImagen4!: string;
  cliente!: Cliente;
  equipo!: EquipoCliente;
}
